[tool.poetry]
name = "crouton"
version = "0.1.4"
description = "A repository to enable API CRUD Routing"
authors = ["Jacob Stewart <jacob@swarmauri.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/swarmauri/crouton"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fastapi = "*"
databases = "*"
SQLAlchemy-Utils = "*"
httpx = "*"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0"  # Add flake8 as a development dependency
pytest = "^8.0"  # Ensure pytest is also added if you run tests
pytest-asyncio = ">=0.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]

log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

asyncio_default_fixture_loop_scope = "function"
